spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://chenc.link:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
logging:
  level:
    root: warn
    com.chenc: info
  file: log/blog-pro.log
#server:
#  port: 8080